"""
disclosure_pack.py — ASC 606 Disclosure Package PDF generator.

Endpoint:
    GET /reports/disclosure-pack?fiscal_year=2025&as_of_date=2025-12-31

Returns a PDF with three sections:
  1. Revenue Disaggregation (by product, current FY vs prior FY)
  2. Deferred Revenue Rollforward
  3. Remaining Performance Obligations (RPO)
"""
from __future__ import annotations

import tempfile
from datetime import date

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from sqlmodel import Session

from ..db import get_session
from ..services.disclosure_service import (
    get_contract_balances_rollforward,
    get_revenue_disaggregation,
    get_rpo,
)

router = APIRouter(prefix="/reports", tags=["disclosure-pack"])

# ─────────────────────────────────────────────────────────────────────────────
# Styles
# ─────────────────────────────────────────────────────────────────────────────

_NAVY = colors.HexColor("#1e3a5f")
_STEEL = colors.HexColor("#2e6da4")
_ROW_ALT = colors.HexColor("#f0f4f8")
_GRID_COLOR = colors.HexColor("#cccccc")


def _styles():
    s = getSampleStyleSheet()
    s.add(ParagraphStyle("DiscTitle", parent=s["Title"], fontSize=20, spaceAfter=16,
                         textColor=_NAVY, alignment=1))
    s.add(ParagraphStyle("DiscSubtitle", parent=s["Normal"], fontSize=12, spaceAfter=8,
                         textColor=_STEEL, alignment=1))
    s.add(ParagraphStyle("DiscH1", parent=s["Heading1"], fontSize=13, spaceAfter=8,
                         textColor=_NAVY, spaceBefore=4))
    s.add(ParagraphStyle("DiscBody", parent=s["BodyText"], fontSize=9, spaceAfter=6,
                         leading=13))
    s.add(ParagraphStyle("DiscNote", parent=s["BodyText"], fontSize=8, spaceAfter=4,
                         textColor=colors.grey, leading=11))
    return s


def _base_table_style(num_rows: int) -> TableStyle:
    """TableStyle with alternating row backgrounds (manually applied)."""
    cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, _GRID_COLOR),
    ]
    for i in range(1, num_rows):
        if i % 2 == 0:
            cmds.append(("BACKGROUND", (0, i), (-1, i), _ROW_ALT))
    return TableStyle(cmds)


def _total_row_style() -> TableStyle:
    return TableStyle([
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("LINEABOVE", (0, -1), (-1, -1), 1, _NAVY),
    ])


# ─────────────────────────────────────────────────────────────────────────────
# PDF builder
# ─────────────────────────────────────────────────────────────────────────────

def _build_pdf(fiscal_year: int, as_of_date: date, session: Session) -> str:
    """Assemble the disclosure PDF and return its temp file path."""
    styles = _styles()

    tmp = tempfile.NamedTemporaryFile(
        suffix=".pdf", delete=False, prefix=f"disclosure_fy{fiscal_year}_"
    )
    tmp.close()

    doc = SimpleDocTemplate(
        tmp.name,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.85 * inch,
        rightMargin=0.85 * inch,
    )
    story = []

    # ── Title page ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1.2 * inch))
    story.append(Paragraph("ASC 606 Disclosure Package", styles["DiscTitle"]))
    story.append(Paragraph(f"Fiscal Year {fiscal_year}", styles["DiscTitle"]))
    story.append(Spacer(1, 0.25 * inch))
    story.append(Paragraph(f"As of {as_of_date.strftime('%B %d, %Y')}", styles["DiscSubtitle"]))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph(
        "Revenue from Contracts with Customers · Generated by AccrueSmart",
        styles["DiscNote"],
    ))
    story.append(PageBreak())

    # ── Section 1: Revenue Disaggregation ─────────────────────────────────────
    story.append(Paragraph("1.  Disaggregation of Revenue", styles["DiscH1"]))
    story.append(Paragraph(
        f"The following table disaggregates recognized revenue by performance obligation "
        f"for fiscal year {fiscal_year} compared to the prior year {fiscal_year - 1}. "
        f"Revenue is presented net of adjustments.",
        styles["DiscBody"],
    ))
    story.append(Spacer(1, 0.1 * inch))

    disagg = get_revenue_disaggregation(session, fiscal_year)
    if disagg:
        headers = ["Performance Obligation", f"FY {fiscal_year}", f"FY {fiscal_year - 1}", "Variance"]
        rows = [headers]
        for d in disagg:
            sign = "+" if d["variance_pct"] >= 0 else ""
            rows.append([
                f"{d['product_name']}  ({d['product_code']})",
                f"${d['current']:,.2f}",
                f"${d['prior']:,.2f}",
                f"{sign}{d['variance_pct']:.1f}%",
            ])
        total_curr = sum(d["current"] for d in disagg)
        total_prior = sum(d["prior"] for d in disagg)
        total_var = ((total_curr - total_prior) / total_prior * 100) if total_prior else 0.0
        sign = "+" if total_var >= 0 else ""
        rows.append(["Total", f"${total_curr:,.2f}", f"${total_prior:,.2f}", f"{sign}{total_var:.1f}%"])

        t = Table(rows, colWidths=[3.0 * inch, 1.3 * inch, 1.3 * inch, 1.0 * inch])
        t.setStyle(_base_table_style(len(rows)))
        t.setStyle(_total_row_style())
        story.append(t)
    else:
        story.append(Paragraph(
            "No recognized revenue data found for this fiscal year.", styles["DiscBody"]
        ))

    story.append(PageBreak())

    # ── Section 2: Deferred Revenue Rollforward ───────────────────────────────
    story.append(Paragraph("2.  Contract Balances — Deferred Revenue Rollforward", styles["DiscH1"]))
    story.append(Paragraph(
        f"The following table presents the rollforward of contract liabilities (deferred revenue) "
        f"for fiscal year {fiscal_year}. Beginning balance represents unrecognized revenue from "
        f"contracts entered prior to the fiscal year. Additions represent the total allocated "
        f"transaction price for contracts entered during the fiscal year.",
        styles["DiscBody"],
    ))
    story.append(Spacer(1, 0.1 * inch))

    balances = get_contract_balances_rollforward(session, fiscal_year)
    dr = balances.get("deferred_revenue", {})

    rows = [
        ["", "Amount"],
        [f"Beginning balance — January 1, {fiscal_year}", f"${dr.get('beginning', 0):,.2f}"],
        ["Additions — new contracts entered during period", f"${dr.get('additions', 0):,.2f}"],
        ["Revenue recognized during period", f"(${dr.get('recognized', 0):,.2f})"],
        [f"Ending balance — December 31, {fiscal_year}", f"${dr.get('ending', 0):,.2f}"],
    ]
    t = Table(rows, colWidths=[4.0 * inch, 1.6 * inch])
    t.setStyle(_base_table_style(len(rows)))
    t.setStyle(TableStyle([
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("LINEABOVE", (0, -1), (-1, -1), 1, _NAVY),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(
        "Note: Amounts in parentheses represent revenue recognized and removed from the deferred balance.",
        styles["DiscNote"],
    ))

    story.append(PageBreak())

    # ── Section 3: Remaining Performance Obligations ──────────────────────────
    story.append(Paragraph("3.  Remaining Performance Obligations (RPO)", styles["DiscH1"]))
    story.append(Paragraph(
        f"The following table presents the aggregate transaction price allocated to performance "
        f"obligations that are unsatisfied (or partially unsatisfied) as of "
        f"{as_of_date.strftime('%B %d, %Y')}. The company expects to recognize this revenue "
        f"over the periods indicated below.",
        styles["DiscBody"],
    ))
    story.append(Spacer(1, 0.1 * inch))

    rpo = get_rpo(session, as_of_date)
    total_rpo = sum(rpo.values())

    rows = [["Recognition Period", "Amount"]]
    for bucket, amt in rpo.items():
        rows.append([bucket, f"${amt:,.2f}"])
    rows.append(["Total RPO", f"${total_rpo:,.2f}"])

    t = Table(rows, colWidths=[3.0 * inch, 1.6 * inch])
    t.setStyle(_base_table_style(len(rows)))
    t.setStyle(_total_row_style())
    story.append(t)

    if total_rpo == 0:
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(
            "No remaining performance obligations exist after the reporting date.",
            styles["DiscBody"],
        ))

    doc.build(story)
    return tmp.name


# ─────────────────────────────────────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────────────────────────────────────

@router.get("/disclosure-pack")
def generate_disclosure_pack(
    fiscal_year: int = Query(..., ge=2000, le=2100, description="Fiscal year, e.g. 2025"),
    as_of_date: date = Query(..., description="As-of date for RPO (YYYY-MM-DD)"),
    session: Session = Depends(get_session),
):
    """Generate and download ASC 606 Disclosure Package as PDF."""
    try:
        filepath = _build_pdf(fiscal_year, as_of_date, session)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}") from exc

    filename = f"ASC606_Disclosure_FY{fiscal_year}_{as_of_date}.pdf"
    return FileResponse(
        filepath,
        media_type="application/pdf",
        filename=filename,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/disclosure-pack/data")
def get_disclosure_data(
    fiscal_year: int = Query(..., ge=2000, le=2100),
    as_of_date: date = Query(...),
    session: Session = Depends(get_session),
):
    """Return disclosure data as JSON (same data that goes into the PDF)."""
    return {
        "fiscal_year": fiscal_year,
        "as_of_date": as_of_date.isoformat(),
        "revenue_disaggregation": get_revenue_disaggregation(session, fiscal_year),
        "contract_balances": get_contract_balances_rollforward(session, fiscal_year),
        "rpo": get_rpo(session, as_of_date),
    }
